// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOl9qMc3jx_uX24Hq8RaeDPfaXdT-rijM',
    appId: '1:231467643985:android:95771d27c8395f1f62f470',
    messagingSenderId: '231467643985',
    projectId: 'khyosr23',
    storageBucket: 'khyosr23.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdd5Aqw6G7NHoMCj4AydRpKPoSdBlI8pk',
    appId: '1:231467643985:ios:63f007eea253135862f470',
    messagingSenderId: '231467643985',
    projectId: 'khyosr23',
    storageBucket: 'khyosr23.firebasestorage.app',
    iosBundleId: 'com.example.flutterr2',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCX5X9u_ncD0scUhhdnS15JeyHpGaEwsIY',
    appId: '1:231467643985:web:ce1513c5c3229f3f62f470',
    messagingSenderId: '231467643985',
    projectId: 'khyosr23',
    authDomain: 'khyosr23.firebaseapp.com',
    storageBucket: 'khyosr23.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdd5Aqw6G7NHoMCj4AydRpKPoSdBlI8pk',
    appId: '1:231467643985:ios:63f007eea253135862f470',
    messagingSenderId: '231467643985',
    projectId: 'khyosr23',
    storageBucket: 'khyosr23.firebasestorage.app',
    iosBundleId: 'com.example.flutterr2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCX5X9u_ncD0scUhhdnS15JeyHpGaEwsIY',
    appId: '1:231467643985:web:0f191673081d94d862f470',
    messagingSenderId: '231467643985',
    projectId: 'khyosr23',
    authDomain: 'khyosr23.firebaseapp.com',
    storageBucket: 'khyosr23.firebasestorage.app',
  );

}